### ISSUE TITLE
Enfocus demo site doesn't work.

### ISSUE THREAD

**Issue by tyano** [ckirkendall/enfocus-demo-site#4]
Now enfocus demo site (http://ckirkendall.github.io/enfocus-site/) doesn't work. 

It shows an error message 

```Invalid match arg: /<(?!area|br|col|embed|hr|img|input|link|meta|param)(([\w:]+)[^>]*)\/>/i``` 

to console when I click links on header bar. seems like all buttons on top-bar doesn't work.

I checked it with Firefox 41.0.2 and Safari 9.0.1 on Mac OS X 10.11.1.

**Comment by ckirkendall** [comment]
Ouch, hmmm.  I am using chrome I will try to test it in firefox later.

**Comment by tyano** [comment]
I checked it with Chrome (on Mac), then it works. Hmm... but it doesn't work with Firefox and Safari.
I tested again after removing browser cache, but no change.

**Comment by ckirkendall** [comment]
This has been fixed.
